
 // This code was generated by a tool. Any changes made manually will be lost
 // the next time this code is regenerated.
 // 
 namespace AutomatedScreenshots
 {
        static class Versioning
        {
                public const int major = 0;
                public const int minor = 8;
                public const int patch = 4;
                public const int build = 2;
                public const string Number = "0.8.4.2";
                public const string Text = Number + " Unofficial";
        }
}
